import type { NextPage } from 'next'
import Head from 'next/head';
import Image from 'next/image';
import classes from '../styles/Home.module.scss';
import { Layout, Menu, Button } from 'antd';
import { ShoppingCartOutlined, UserOutlined } from "@ant-design/icons";

const Home: NextPage = () => {
  const { Header, Footer, Sider, Content } = Layout;

  return (
    <div className={classes.container}>
      <Head>
        <title>SVNDZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header className={classes.header}>
          <div className={classes.logo}><Image src="https://cdn.shopify.com/s/files/1/0275/7784/3823/files/logo_white.png?v=1590001197" width={130} height={45}/></div>
          <div key="My Cart" className={classes.headerItem}>
            <ShoppingCartOutlined />
            <span>
              Cart
            </span>
          </div>
          <div key="My Account" className={`${classes.account} ${classes.headerItem}`}>
            <UserOutlined />
            <span>
              Account
            </span>
          </div>
        </Header>
        <Content>
          <main className={classes.main}>
          </main>
        </Content>
      </Layout>
    </div>
  )
}

export default Home
