import type { NextPage } from 'next'
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import classes from '../styles/Home.module.scss';
import { Layout, Carousel, Row, Col, Typography, Card, Form, Input, Button, Divider } from 'antd';
import { InstagramOutlined } from "@ant-design/icons";
import {ProductItem, FooterComp, CarouselComp} from '../components';

interface HomePageProps {
  collections: any,
  router: any,
}

const HomePage = ({collections, router}:HomePageProps) => {
  const { Header, Footer, Sider, Content } = Layout;
  const { Title } = Typography;
  const { Meta } = Card;

  const handleViewAll = () => {
    router.push('/collections/all')
  }

  return (
    <div className={classes.container}>
      <Head>
        <title>SVNDZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>
      <Layout>
        <Content>
          <main className={classes.main}>
  
            <CarouselComp handleViewAll={handleViewAll}/>
  
            <Row
              className={classes.mixMatchSection}
              data-aos="fade-up"
              data-aos-duration="2000"
            >
              <Row className={classes.mixMatchHeadingContainer}>
                <Title level={1} className={classes.mixMatchHeading}>MIX & MATCH</Title>
              </Row>
              <Row className={classes.products} gutter={[24, 24]}>
                {collections.slice(0,8).map((item:any,index:number) => 
                  <ProductItem item={item} index={index}/>
                )}
              </Row>
              <Col className={classes.btnContainer}>
                <button className={classes.viewAllBtn} onClick={handleViewAll}>VIEW ALL</button>
              </Col>
            </Row>
          </main>
        </Content>
        <Footer className={classes.footer}>
          <FooterComp/>
        </Footer>
      </Layout>
      
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <script>
        AOS.init();
      </script>
    </div>
  )
}

export default HomePage;
